name: CI

permissions:
  contents: read

on:
  pull_request:
    branches: [main]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".golangci*"
  push:
    branches: [main]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".golangci*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0

      - name: govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@v1.3.0 ./...

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod Verify
        run: go mod verify

      - name: Build
        run: go build -o /dev/null ./...

      - name: Test
        run: go test -v -count=1 -race -shuffle=on -coverprofile=coverage.txt ./...

      - name: Coverage summary
        run: go tool cover -func=coverage.txt >> "$GITHUB_STEP_SUMMARY"
